### ISSUE TITLE
Montar rich-picture

### ISSUE THREAD

**Issue by Matheusafonsouza** [UnBArqDsw2021-2/2021.2_G5_Garimpei#1]
## Descreva o tipo de solução que é esperada
Elaboração de rich pictures para levantar os casos de uso e funcionalidades da aplicação.

## Critérios de aceite
- Elaboração do rich picture
- Elaboração da página na wiki de documentação do rich picture

**Comment by VictorJorgeFGA** [comment]
![rich_picture_arqdsw](https://user-images.githubusercontent.com/43304761/151818376-c79625e9-de18-4137-93f4-bbafd2b9ca71.png)

**Comment by twistershark** [comment]
![Rich Picture - Paulo](https://user-images.githubusercontent.com/25483313/151905857-845e8295-36d8-422b-89dd-d19438bae1fb.png)

**Comment by Matheusafonsouza** [comment]
Rich picture usuário comprador
![image](https://user-images.githubusercontent.com/42722634/151908536-b475c8ac-a957-47d7-a08e-fe94221f0ddd.png)

Rich picture usuário vendedor
![image](https://user-images.githubusercontent.com/42722634/151908566-842a2960-193d-4808-a1ad-4f268f8cc977.png)

**Comment by thiagompc** [comment]
![image](https://user-images.githubusercontent.com/53379532/151909166-1e8d7fea-2835-4bd7-ab6f-cd8348d4c291.png)

**Comment by julianavalle** [comment]
![richPictureJuliana](https://user-images.githubusercontent.com/62117139/151912218-005e218b-3117-4793-be49-292a15826131.png)

**Comment by viniciussaturnino** [comment]
![RichPicture_Garimpei](https://user-images.githubusercontent.com/49040839/151978931-a3f96312-bb3b-45cc-a739-c5e914832116.png)

**Comment by daniel-bm** [comment]
![Rich Picture@2x](https://user-images.githubusercontent.com/38585724/151985111-baa47f49-341c-4f50-91ff-e669bc182e78.png)

**Comment by matgomes21** [comment]
![RichPicture_MateusGomes](https://user-images.githubusercontent.com/50213406/151990593-140c3bdd-427d-4fb6-9ebd-badb4c4896d3.jpg)

**Comment by DenysRogeres** [comment]
![image](https://user-images.githubusercontent.com/54676096/152093778-0d66e584-f92b-4a8d-baab-0de770e7664f.png)

**Comment by Matheusafonsouza** [comment]
@matgomes21 faz a página da wiki dos rich-pictures, please
