### ISSUE TITLE
Priorização

### ISSUE THREAD

**Issue by Matheusafonsouza** [UnBArqDsw2021-2/2021.2_G5_Garimpei#18]
## Descreva o tipo de solução que é esperada
Realizar a priorização dos requisitos funcionais e não funcionais levantados, utilizando o método MoSCoW.

## Critérios de aceite
- Priorização de todos os requisitos levantados
- Elaboração da wiki de documentação para a priorização

**Comment by twistershark** [comment]
https://docs.google.com/spreadsheets/d/12uJ9KuDaZ50HpenzzUZCfym6KgpdQel8c5v5OL5VCNU/edit

**Comment by Matheusafonsouza** [comment]
@twistershark vou subir as coisas pra wiki

**Comment by Matheusafonsouza** [comment]
@DenysRogeres @daniel-bm vocês que tão cuidando do backlog né? quando subirem ele, sobe isso junto (uma coluna no backlog)
