### ISSUE TITLE
Protótipo baixa fidelidade

### ISSUE THREAD

**Issue by Matheusafonsouza** [UnBArqDsw2021-2/2021.2_G5_Garimpei#22]

**Comment by DenysRogeres** [comment]
Realizei esse protótipo baseado em algumas plataforma como Olx, Enjoei e Mercado Livre.

![image](https://user-images.githubusercontent.com/54676096/151903802-71cea2f7-0909-45f2-abe5-0963b99dd431.jpeg)
![image](https://user-images.githubusercontent.com/54676096/151903813-7a97a0f5-27ae-493f-8c1c-584faeafe104.jpeg)
![image](https://user-images.githubusercontent.com/54676096/151903827-d7cc1a95-d7b1-4714-92f0-e6120a068cc7.jpeg)

**Comment by twistershark** [comment]
Adicionando protótipo de uma homepage com o objetivo de oferecer alguns produtos em destaque para o usuário enquanto permite que facilmente ele busque por algo que é do seu interesse atual.

![Prototipo - Homepage - Paulo](https://user-images.githubusercontent.com/25483313/151906763-c2243d00-ebcf-4f30-88bc-23ce05858842.png)

**Comment by Matheusafonsouza** [comment]
Realizei a elaboração do protótipo de baixa fidelidade para a tela inicial e a tela de produto, focando mais na disposição e tamanho dos elementos em tela
![WhatsApp Image 2022-02-01 at 00 35 20 (1)](https://user-images.githubusercontent.com/42722634/151909450-8d2ee610-58f1-4b83-ae77-ad7c83b477b8.jpeg)

![WhatsApp Image 2022-02-01 at 00 35 16 (1)](https://user-images.githubusercontent.com/42722634/151909453-74476d6e-36ce-4d11-8a3f-e76ab0281d07.jpeg)
.

**Comment by daniel-bm** [comment]
Protótipo de baixa fidelidade da tela inicial e da exibição de um produto específico
![20220201_063527](https://user-images.githubusercontent.com/38585724/151944919-9d084d28-6ac6-4307-ab3d-788f4dcbe97d.jpg)
![20220201_063535](https://user-images.githubusercontent.com/38585724/151944924-f2fb224e-f094-424b-92f9-9b423e4c18e6.jpg)

**Comment by julianavalle** [comment]
[prototipo_baixa_juliana.pdf](https://github.com/UnBArqDsw2021-2/2021.2_G5_Garimpei/files/7979172/prototipo_baixa_juliana.pdf)

**Comment by julianavalle** [comment]
![prototipo_baixa_juliana](https://user-images.githubusercontent.com/62117139/151987321-98c1124f-9e3f-4052-9cb9-cfc0d7808bcc.jpeg)

**Comment by VictorJorgeFGA** [comment]
Prototipo de baixa fidelidade com: Tela de login, home page e descrição de anúncio.
Link para testar: https://www.figma.com/proto/yNLgoTJq8ADrsuzvDgxotT/Prototipo_baixa_garimpei?node-id=2%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2%3A2

Print:
![image](https://user-images.githubusercontent.com/43304761/152002138-fdb3d67d-ed0d-4d34-ac69-eff26b26a4e6.png)

**Comment by Matheusafonsouza** [comment]
@VictorJorgeFGA Esse protótipo tá pra média fidelidade, por contar com imagens, textos e etc...
Mas vamos seguir, tá ótimo de qualquer maneira :-)

**Comment by thiagompc** [comment]
![image](https://user-images.githubusercontent.com/53379532/152078393-26388122-c1cb-45b4-9682-cbdeb3873bef.png)

**Comment by Matheusafonsouza** [comment]
@daniel-bm ou @VictorJorgeFGA, façam uma página na wiki com os protótipos de baixa fidelidade levantados aqui
Coloquem qual integrante fez, qual página é e outras informações que acharem importante
Não precisa ter pressa pra isso, podem lidar com prioridade mais baixa
