### ISSUE TITLE
Desenvolver mapa mental

### ISSUE THREAD

**Issue by Matheusafonsouza** [UnBArqDsw2021-2/2021.2_G5_Garimpei#23]

**Comment by twistershark** [comment]
![mapamental-comfundo](https://user-images.githubusercontent.com/25483313/152181060-d968b7e5-f0af-43a5-bc16-23cc76035dd5.png)
![mapamental-semfundo](https://user-images.githubusercontent.com/25483313/152181081-6a934932-f2c6-46bf-a87a-15265d2cd617.png)
