### ISSUE TITLE
Protótipo de média fidelidade

### ISSUE THREAD

**Issue by Matheusafonsouza** [UnBArqDsw2021-2/2021.2_G5_Garimpei#28]
## Descreva o tipo de solução que é esperada
Elaboração do protótipo de média fidelidade

## Critérios de aceite
- Elaboração do protótipo de média fidelidade
- Elaboração da wiki de documentação para o protótipo de média fidelidade

**Comment by DenysRogeres** [comment]
![image](https://user-images.githubusercontent.com/54676096/151903462-62da90b3-919c-463b-ad84-695a9744de03.jpeg)
![image](https://user-images.githubusercontent.com/54676096/151903478-1ad2bb6d-8ef3-454d-b83e-6915d8e84c2d.jpeg)
![image](https://user-images.githubusercontent.com/54676096/151903498-af08831d-5e3d-4867-a46f-1b59733b9a55.jpeg)

Realizei esse protótipo baseado em algumas plataformas como enjoei, Olx e Mercado Livre.
