### ISSUE TITLE
Instrospecção

### ISSUE THREAD

**Issue by Matheusafonsouza** [UnBArqDsw2021-2/2021.2_G5_Garimpei#29]

**Comment by twistershark** [comment]
Funcionais:
- O usuário deve poder vender algo que não usa mais.
- O usuário deve poder enviar mais de uma foto do produto no processo de cadastro.
- O usuário deve poder criar uma nova categoria de produtos.
- O usuário deve poder ver o contato do vendedor para efetuar a compra.
- O usuário deve poder avaliar um vendedor.
- O administrador de uma comunidade deve poder cadastrar outros membros da comunidade.
- O usuário deve poder criar novas comunidades. 
- O usuário deve poder procurar por produtos pelo nome.
- O usuário deve poder ver os produtos de diferentes comunidades.
- O usuário deve poder comprar um item independente da localização do vendedor.

Não Funcionais:
- O usuário deve poder usar qualquer tipo de dispositivo para acessar o sistema.
- O usuário deve ter garantia de que seus dados estão seguros.
- O usuário deve poder encontrar o garimpei em mecanismos de busca na internet.

**Comment by VictorJorgeFGA** [comment]
| ID | Requisito |
| :-: | :---------:  |
| 1 | usuário deve ser capaz de ver o contato do vendedor em um anuncio |
| 2 | a aplicação deve assegurar que o numero cadastrado é do usuário |
| 3 | o usuário deve ser capaz de encerrar um anuncio dele |
| 4 | o usuario deve ser capaz de excluir um anuncio dele |
| 5 | o usuário deve ser capaz de anexar fotos ao anuncio |
| 6 | o usuário deve ser capaz de fazer perguntas no anúncio |
| 7 | o usuário anunciante deve ser capaz de responder perguntas no anuncio |
| 8 | um usuário deve ser capaz de avaliar outro usuário |
| 9 | um usuário deve ser capaz de reportar outro usuário à moderação |
| 10 | um usuário deve ser capaz de sair de uma comunidade |
| 11 | o lider de uma comunidade de ser capaz de adiconar e remover novos usuários |
| 12 | o usuário deve ser capaz de excluir sua conta |
| 13  | o usuário deve ser capaz de procurar anuncios por palavra-chave |
| 14 | o usuário deve ser capaz de favoritar uma comunidade |
| 15 | o usuário deve ser capaz de favoritar um anuncio |
| 16 | o usuário deve ser capaz de favoritar um outro usuário |
| 17 | o usuário deve ser capaz de indicar o endereço de físico em um anuncio |

**Comment by matgomes21** [comment]
<html>
<body>


ID | Requisitos Funcionais
-- | --
1 | O usuário deve ser capaz de criar uma conta
2 | O usuário deve ser capaz de efetuar login
3 | O usuário deve ser capaz de efatuar logout
4 | O usuário deve ser capaz de criar uma comunidade
5 | O usuário deve ser capaz de pesquisar um produto
6 | O usuário deve ser capaz de favoritar um produto
7 | O usuário deve ser capaz de anunciar um produto por meio de uma comunidade
8 | O usuário deve ser capaz de editar seus anúncios
9 | O usuário deve ser capaz de administrar sua comunidade

ID | Requisitos Não Funcionais
-- | --
1 | O usuário deve ser capaz de acessar o sistema por qualquer dispositivo
2 | O usuário deve ter seus dados protegidos por criptografia
3 | O usuário deve ter garantia que suas comunidades não podem ser acessadas por usuários não autorizados
 

</body>
</html>

**Comment by Matheusafonsouza** [comment]
<html>
<body>


ID | Requisitos Funcionais
-- | --
1 | O usuário deve ser capaz de criar uma conta
2 | O usuário deve ser capaz de efetuar login
3 | O usuário deve ser capaz de efetuarlogout
4 | O usuário deve ser capaz de criar uma comunidade
5 | O usuário deve ser capaz de adicionar usuários em uma comunidade
6 | O usuário deve ser capaz de pesquisar um produto
7 | O usuário deve ser capaz de favoritar um produto
8 | O usuário deve ser capaz de anunciar um produto caso seja de uma comunidade
9 | O usuário deve ser capaz de editar seus produtos
10 | O usuário deve ser capaz de comprar um produto
11 | O usuário deve ser capaz de entrar em contato com o vendedor do produto

ID | Requisitos Não Funcionais
-- | --
1 | O usuário deve ser capaz de acessar o sistema por qualquer dispositivo
2 | O usuário deve ter seus dados protegidos
 

</body>
</html>

**Comment by Matheusafonsouza** [comment]
Já tá bom de requisitos levantados por instrospecção, vou subir eles pra wiki
A partir de agora não precisa mais contribuir nessa issue
