### ISSUE TITLE
Primeira Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2021-2/2021.2_G5_Garimpei#41]
Olá Pessoal!

O Grupo 05 irá avaliar o Grupo 06 nessa primeira avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta acessar o Tópico 2 DSW(Base) no Moodle, e procurar por "Primeira Avaliação por Pares".

Deadline: 07 de Fevereiro de 2022, ao final do dia, conforme consta no cronograma.

Atenciosamente.

**Comment by Matheusafonsouza** [comment]
@mileneserrano Tranquilo professora! Vamos todos avaliar o grupo 06 até o deadline informado. Uma ótima noite para você!
