### ISSUE TITLE
Montar questionário para elicitação

### ISSUE THREAD

**Issue by Matheusafonsouza** [UnBArqDsw2021-2/2021.2_G5_Garimpei#7]

**Comment by twistershark** [comment]
![Screen Shot 2022-02-01 at 11 48 43](https://user-images.githubusercontent.com/25483313/151990665-eac51b47-c878-4ce2-a069-88a97bf4d340.png)
![Screen Shot 2022-02-01 at 11 48 54](https://user-images
![Screen Shot 2022-02-01 at 11 49 06](https://user-images.githubusercontent.com/25483313/151990744-ce72d493-d49e-46ea-ae04-f0799825591d.png)
.githubusercontent.com/25483313/151990708-1fcc2667-18fd-4624-b4
![Screen Shot 2022-02-01 at 11 49 16](https://user
![Screen Shot 2022-02-01 at 11 49 25](https://user-images.githubuserc
![Screen Shot
![Screen Shot 2022-02-01 at 11 49 42](https://user-images.githubusercontent.com/25483313/151990871-d3ec5eb3-f470-4447-a4f8-a03fd1b597e5.png)
 2022-02-01 at 11 49 35](https://user-images.githubusercontent.com/25483313/151990846-f90e3dba-b350-47f8-ab7a-278304aa523d.png)
ontent.com/25483313/151990805-61d3d03e-ab48-47e9-9d0d-ad02f32b0c00.png)
-images.githubusercontent.com/25483313/151990785-1f33409d-3100-4953-9faa-ad0580cd7ea2.png)
99-7aae90d84795.png)
